const text = [
  `India was the first country to mine diamonds. From the 4th century BC for around 1,000 years, India was the only source of diamonds in the world. The original diamonds were found in the Krishna River Delta. In the 18th century, more diamond deposits were discovered in Brazil, and soon after, in South Africa, adding to the market of diamonds.`,
  `Around 70% of the world’s spices come from India. India is by far the largest producer of spices, which are shipped across continents to restaurants and kitchens worldwide. Some of the best-known spices are turmeric, cumin, saffron, and chili powders.`,
  `India is the wettest inhabited place on Earth. Meghalaya village has won the Guinness world record title for the wettest place on Earth, with about 11,873 milliliters of rain annually. The monsoon season lasts six months, so make sure you pack an umbrella!`,
  `Rajasthan has a Temple of Rats.The animal wonders of India continue. Although rats might not be the first species you think of to worship, there is a temple in Rajasthan dedicated to rats. Thousands of rats call the temple home, making it one of the country’s most unique attractions. Many pilgrims visit the temple every year on their own religious journeys, so make sure to be respectful of local customs when visiting.`,
  `The world’s largest sundial is located in India. The town of Jaipur is home to the largest sundial in the world, which is a towering 27 meters (90 feet) tall! The sundial is constructed from beautiful polished stone to create an awe-inspiring work of architecture. The sundial has been listed as a UNESCO World Heritage Site. Every year, it attracts thousands of visitors, who come to witness the shadow moving at about six centimeters per minute.`,
  `Home of a mysterious skeleton lake. Located in the Himalayas at about 16,470 feet, the glacial Lake Roopkund has become famous for the human skeletons found in the lake and surrounding areas. It is thought that the skeletons are the remains of people from the 9th century who perished during a severe hail storm.  `,
  `The steel wires in the Bandra Worli Sealink could stretch around the world. Completed in 2010, the incredible Bandra Worli Sealink bridge required 90,000 tons of cement to build. To hold that all up, enormous steel cables – each with the ability to hold up 900 tons of weight – were put in place along the bridge. If they were laid out end to end, the cables could reach around the circumference of the globe.`,
  `“Indian food” has become one of the most widespread cuisines in the world. From London to New York City, Indian food has spread across the world and continues to gain popularity. Many argue that authentic flavor and spice is lost in many of the restaurants outside of India itself.`,
  `India has the highest population of vegetarians. It’s estimated that between 15% and 30% of India’s population follow a strict vegetarian diet, while many others will only consume fish and no land animals. Vegetarianism is so widely spread that even western food chains like KFC provide a vegetarian menu for restaurant patrons.`,
  `Shampoo originated in India. The word “shampoo” comes from the Sanskrit word “champu,” which means “to massage.”. Ground herbs mixed with water were the very first forms of shampoo. Not until later, when the idea caught on were commercial bottles produced.`,
  `India was the first country to refine and consume sugar. India was the first place were sugar was extracted, refined, and used in cooking – although once people got a taste of the delicious stuff, sugar production quickly spread around the world.`,
  `North Sentinel Island is one of the last “untouched” places on Earth. The Indian government has prohibited anyone from going within three miles of North Sentinel Island, home of the Sentinelese people.`,
];
export default text;
